public class freshDeskResult{
	public boolean active;
	public String address;
	public String company_id;
	public String description;
	public String email;	
	public Integer id;	
	public String job_title;
	public String language;	
	public String mobile;
	public String name;	
	public String phone;
	public String time_zone;	
	public String twitter_id;
	public String created_at;	
	public String updated_at;	 
	
	public class custom_fields {
		public String department;	//Admin
		public boolean permanent;
	}

	
}